export type IGirl = {
  id: number,
  user_id: number,
  image: string,
  name: string,
  rarity: string,
  state: "feed"|"dance_ready"|"dance"|"sleep"|"stake",
  exp: number,
  exp_limit: number,
  level: number,
  box_points: number[],
  feed_started_at: number,
  feed_price: number,
  feed_multiplier: number,
  token_balance: number,
  token_per_feed: number,
  slot_index: number,
}

export const MOCK_GIRL: IGirl = {
  id: 1,
  user_id: 1,
  image: "1-common.png",
  name: "Lolly chan",
  rarity: "Uncommon",
  state: "feed",
  exp: 0,
  exp_limit: 20,
  level: 1,
  box_points: [5, 12],
  feed_started_at: 1,
  feed_price: 1,
  feed_multiplier: 1,
  token_balance: 0,
  token_per_feed: 0.04,
  slot_index: 1,
};
